** Homework six (25 Points)**

• (Reading) Ch5, Machine Learning [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/), up to and including Linear Regression; and the in-class reading ** cross_validation_forEconomists ** on polylearn. 

• (UnGraded) DataCamp chapter in Supervised Learning with scikit-learn: **Regression** and **Fine Tuning Your Model**. For the Tuning chapter focus on the lessons including and following (Hyperparameter tuning). Quiz questions will be from these chapters and the reading.

• (Graded) Below notebook on fine tuning your model. If you're working in a group (max 3 people) please do submit it as a group. Submit only one assignment. You will both receive credit. This homework is longer and will count as hw6 and hw7 - 20 points. The code is very similar to our in-class exercise, therefore, points are granted for understanding of the output. 

In [66]:
# Import Modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline  
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import RidgeCV
from sklearn.grid_search import GridSearchCV
from sklearn.cross_validation import KFold
from sklearn.cross_validation import cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn.cross_validation import train_test_split
from sklearn.preprocessing import PolynomialFeatures

In [67]:
# Load the Ladybug data
'''In 1983 an article was published about ladybird beetles and their 
behavior changes under different temperature conditions (N. H. Copp. Animal Behavior, 31,:424-430). 
An experiment was run to see how many beetles stayed in light as temperature changed.
'''

# Read the CSV file into a DataFrame: df
df = pd.read_csv("LadyBugs.csv")

# Create arrays for features (Lighted) and target variable (Temp)
yp = df[['Lighted']]
xp = df[['Temp']]

In [68]:
# Show the first 5 observations (1 point)
# your code here
df.head()

Temp  Lighted
0    -2       28
1    -1       29
2     0       22
3     1       28
4     2       34

# Linear Regression, Part I  

In [69]:
# (1 point)
# Create training and test sets with 0.3 test size
xr_train, xr_test, yr_train, yr_test = train_test_split(xr, yr, test_size = 0.3)

# Create linear regression object call ols
ols = LinearRegression()
ols
  
# Train the model using the training sets
# your code here
ols.fit(xr_train, yr_train)
# Report the coefficient 
# your code here  
ols.coef_

array([[ 0.00000000e+00, -1.10556068e-10, -1.08683189e-12,
         4.73740107e-13,  5.30569126e-12,  5.45242719e-11,
         5.00352030e-10,  3.88485318e-09,  2.29017719e-08,
         7.69672632e-08, -1.75303687e-08,  1.60807101e-09,
        -7.75419887e-11,  2.08146201e-12, -2.95371196e-14,
         1.73269314e-16]])

## Plot outputs

In [74]:
# (1 point)
# This plots the predicted ols fitted line

predictor_space = pd.DataFrame(np.arange(min, max,  0.05))
predicor_poly = pd.DataFrame(poly.fit_transform(predictor_space))
plt.plot(predictor_space, ridge_final.predict(predictor_poly), color = 'blue'
# Scatter plot the actual test data 
# your code here
plt.scatter(xl_test.iloc[:, [1]], yl_test, color = 'blue')

SyntaxError: invalid syntax (<ipython-input-74-63110d016d17>, line 9)

## Predict on the Test data

In [75]:
# Get the predicted y_pred using the test data
y_pred = ols.predict(xr_test)

# Compute and print the R^2 and RMSE
print("R^2: {}".format(ols.score(xr_test, yr_test)))
rmse = np.sqrt(mean_squared_error(yr_test, y_pred))
print("Root Mean Squared Error: {}".format(rmse))

R^2: 0.12863410613499016
Root Mean Squared Error: 12.605193505046667


## a. Does this plot look like a good fit to the data? # (1 point)
No, the rmse is very large
## b. What do out of sample metrics tell you? (1 point)
### the sample metrics don't represent the data

# Polynomial Regression, Part II

In [78]:
#(2 points)
# Reload the CSV file into a DataFrame: df
df = pd.read_csv("LadyBugs.csv")

# Create arrays for features (Lighted) and target variable (Temp)
yl = df[['Lighted']]
xl = df[['Temp']]

# Add in 15-degree polynomial of the X variables
poly = PolynomialFeatures(degree = 15)
xl = pd.DataFrame(poly.fit_transform(xl))
print("Dimensions of X after reshaping: {}".format(xl.shape))

# Create training and test sets with .3 test size
# your code here
xl_train, xl_test, yl_train, yl_test = train_test_split(xl, yl, test_size = 0.3)
# Create linear regression object, ols2
# your code here
ols2 = LinearRegression()
# Fit the model using the training sets 
# your code here
ols2.fit(xl_train, yl_train)
# Report the coefficients
# your code here                    
ols2.coef_

Dimensions of X after reshaping: (44, 16)


array([[ 0.00000000e+00,  1.53701130e-11,  1.09024503e-12,
         4.31478604e-13,  4.87753867e-12,  5.07119226e-11,
         4.71508829e-10,  3.71234085e-09,  2.22056094e-08,
         7.57784778e-08, -1.70197071e-08,  1.54351067e-09,
        -7.37244032e-11,  1.96344611e-12, -2.76824092e-14,
         1.61534268e-16]])

## Plot outputs

In [77]:
#(1 point)
# This plots the predicted ols fitted line
predictor_space = pd.DataFrame(np.arange(min, max, 0.05)) # Creates prediction space on x interval
predictor_poly = pd.DataFrame(poly.fit_transform(predictor_space)) # Creates data to predict on
plt.plot(predictor_space, ols2.predict(predictor_poly), color='blue') # Plot fitted model 

# Scatter plot the actual test data
# your code here
plt.scatter(Xp_test.iloc[:,[1]], yp_test, color='black')

TypeError: cannot convert the series to <class 'float'>

## Predict on the Test data

In [80]:
#(1 point)
# Predict on the test data: y_pred
# your code here
y_pred = ols2.predict(xl_test)
# Computer and print R^2 and RMSE
# your code here
print("R^2: {}".format(ridge_final.score(xl_test, yl_test)))
rmse = np.sqrt(mean_squared_error(yl_test, y_pred))
print("Root Mean Squared Error: {}".format(rmse))

R^2: 0.4279876120564059
Root Mean Squared Error: 10.561131790688766


## a. Does this plot look better than the previous OLS plot? (1 point)
yes this plot looks better
## b. Why? What do out of sample metrics tell you? (1 point)
### the mse is lower and the R^2 is higher

# Ridge Regression, Part III

In [60]:
#(1 point)
# Read the CSV file into a DataFrame: df
# your code here

df = pd.read_csv("LadyBugs.csv")

# Create arrays for features (Lighted) and target variable (Temp)
# your code here
yr = df[['Lighted']]
xr = df[['Temp']]
# Add in 15-degree polynomial of the X variables
# your code here
poly = PolynomialFeatures(degree = 15)
xr = pd.DataFrame(poly.fit_transform(xr))
print ("Dimensions of X after reshaping {}".format(xr.shape))
# Create training and test sets
# your code here
xr_train, xr_test, yr_train, yr_test = train_test_split(xr, yr, test_size = 0.3)
# Create a ridge regressor object called ridge with lambda = 0.1
ridge = Ridge(normalize = True, alpha = 0.1)

# Train the ridge model using the training sets (the polynomial factors are in the data)
# your code here
ridge.fit(xr_train, yr_train)
# The coefficients
# your code here
ridge.coef_

Dimensions of X after reshaping (44, 16)


array([[ 0.00000000e+00,  1.21435603e+00, -1.92893705e-03,
        -3.40700796e-04, -1.09976553e-05, -2.77020561e-07,
        -6.15326114e-09, -1.20611906e-10, -1.90141353e-12,
        -1.31360216e-14,  6.94463044e-16,  4.71559737e-17,
         2.03626422e-18,  7.53975419e-20,  2.58150642e-21,
         8.43024549e-23]])

## Plot outputs

In [61]:
#(1 point)
# This plots the predicted ols fitted line
# your code here (see code above in Part II plot outputs for help)
predictor_space = pd.DataFrame(np.arange(min, max, 0.05))
predictor_poly = pd.DataFrame(poly.fit_transform(predictor_space))
plt.plot(predictor_space, ridge_final.predict(predictor_poly), color = 'blue')
# Scatter plot the actual test data
# your code here
plt.scatter(xl_test.iloc[:, [1]], yl_test, color = 'blue')

TypeError: cannot convert the series to <class 'float'>

## a. Does this plot look better than the previous Polynomial plot? (1 point)
## b. Why? What do out of sample metrics tell you? (1 point)
### your answer here

# Get the 5 fold CV Scores (R2) for all 3 models

In [62]:
#(1 points)

#ols
ols_scores = cross_val_score(ols, xl, yl, cv = 5, scoring = 'r2')
print("Cross-validated OLS scores:", ols_scores)

#ols2
poly_scores = cross_val_score(ols2, xp, yp, cv = 5, scoring = 'r2')
# your code here
print("Cross-validated OLS scores:", poly_scores)
# ridge
ridge_scores = cross_val_score(ridge, xr, yr, cv = 5, scoring = 'r2')
# your code here
print("Cross-validated OLS scores:", ridge_scores)

Cross-validated OLS scores: [-2.54060171e+01 -5.74218783e-03 -1.74007772e+01 -3.38514690e+01
 -9.08551523e+14]
Cross-validated OLS scores: [-30.75075459  -0.04556113 -14.29669246  -2.24972457 -29.57476511]
Cross-validated OLS scores: [-2.33809737e+01  2.19479692e-01 -1.09999672e+01 -4.16344039e-01
 -7.06842774e+04]


## Explain which model if any is best and why. (1 point)
### your answer here

# Hyper Tune Lambda, K-fold Grid Search, Ridge Regression, Part IV

In [63]:
#(4 points)

# Read the CSV file into a DataFrame: df
# your code here
df = pd.read_csv('LadyBugs.csv')
# Create arrays for features (Lighted) and target variable (Temp)
# your code here
yl = df[['Lighted']]
xl = df[['Temp']]
# Add in 15-degree polynomial of the X variables
# your code here
poly = PolynomialFeatures(degree = 15)
xl = pd.DataFrame(poly.fit_transform(xl))
print("Dimensios of X after reshaping: {}".format(xl.shape))
# Create training and test sets with 0.3 hold out for test data
# your code here
xl_train, xl_test, yl_train, yl_test = train_test_split(xl, yl, test_size = 0.3)
# Setup a grid of lambdas (aka alphas) called param_grid of 20 lambdas from .001 to 2 
param_grid = {'alpha': np.linspace(0.001, 2.0, num = 20)}

# Create a ridge regressor object called ridge
# your code here
ridge = Ridge(normalize = True, alpha = 0.1)
# Setup the GridSearchCV object called grid_ridge for 5 folds using the param_grid above and ridge object
grid_ridge = GridSearchCV(ridge, param_grid, cv = 5)

# Train the model using the training sets 5 folds for all lambdas!
# your code here
grid_ridge.fit(xl_train, yl_train)
#Get the best lambda
best = grid_ridge.best_params_

# Create a final ridge regressor object called ridge_final using the best lambda from hypertuning
ridge_final = Ridge(alpha = best['alpha'], normalize = True)

# Now fit this model on the test data 
# your code here
ridge_final.fit(xl_test, yl_test)

Dimensios of X after reshaping: (44, 16)


Ridge(alpha=0.10621052631578948, copy_X=True, fit_intercept=True,
   max_iter=None, normalize=True, random_state=None, solver='auto',
   tol=0.001)

## Plot outputs

In [64]:
#(1 point)
# This plots the predicted ols fitted line
predictor_space = pd.DataFrame(np.arange(min, max, 0.05)) # Creates prediction space on x interval
predictor_poly = pd.DataFrame(poly.fit_transform(predictor_space)) # Creates data to predict on
plt.plot(predictor_space, ridge_final.predict(predictor_poly), color='blue') # Plot fitted model 

# Scatter plot the actual test data
# your code here
plt.scatter(xr_test.iloc[:,[1]], yr_test, color = 'black')

yr_pred = ridge.predict(xr_test)

print("R^2: {}".format(ridge.score(xr_test, yr_test)))
rmse = np.sqrt(mean_squared_error(yr_test, yr_pred))
print("Root Mean Squared Error: {}".format(rmse))

TypeError: cannot convert the series to <class 'float'>

## Final scores given tuned lambda

In [65]:
#(1 point)
# Predict on the test data: y_pred
y_pred = ridge_final.predict(xl_test)

# Compute and print R^2 and RMSE
# your code here
print("R^2: {}".format(ridge_final.score(xl_test, yl_test)))
rmse = np.sqrt(mean_squared_error(yl_test, y_pred))
print("Root Mean Squared Error: {}".format(rmse))

R^2: 0.45444993201746275
Root Mean Squared Error: 8.286215833648203


## a. How does your final score (R2) compare to before? (1 point)
## b. What about your fit to the data graphically? (1 point)
## c. Why do you think the fit is better or worse using Ridge and hypertuning your lambda paramater? (2 point)
### your answer here